name: rebolustdo
favicon: null
layout_spectrum: 0.70824
typography_spectrum: 0.61257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#847c69'
    - '#ffffff'
    - '#d7d600'
    - '#339183'
    - '#2d2814'
  brandStrength: 0.5625
  lightness: 0.3902079565450549
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
